### ISSUE TITLE
USER STORY: Matching label size with paper size

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/first-agile-project#2]
As a **warehouse operator**, I can **select the paper size on which to print** so that **the printed label size matches the parcel size**.

## Acceptance Criteria

* Order details include the order ID, the shipping address and the list of items in the parcel.
* The warehouse employee can select the size of the order details from 3 sizes (A4, A5 and A6).
* Font size used is 12 points.

## Tasks

- [ ] Design a “print” icon and add it to the order details page.
- [ ] Design the print layouts for the different page sizes.
- [ ] Create the HTML and CSS for the dropdown menu including the paper sizes.
- [ ] Create the code for the model, viewer and controller.
- [ ] Test the completed functionality.

**Comment by MoniPar** [comment]
This is completed
