### ISSUE TITLE
USER STORY: Create a poll

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/first-agile-project#6]
In order to **collect users' feedback** as an **administrator**, I can **create a poll**

## Acceptance Criteria

* Create a poll with one question and up to 5 answer options to choose from.
* Display answer options as radio buttons.
* Have a clearly highlighted submit button at the end.

## Tasks

- [ ] Develop the template for a poll with one question followed by 5 labelled radio buttons in one column.
- [ ] Design a background to complement the website's scheme.
- [ ] Create the code for counting results.
- [ ] Test the completed functionality.

**Comment by MoniPar** [comment]
This is the core functionality of the admin and should be done first before adding any enhancing factors on the admin side.  However, relative to the first user story, it is less important and can't have both (6 story points) as a must have out of 8 (the % will exceed 60%).
