### ISSUE TITLE
USER STORY: Hide the poll

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/first-agile-project#7]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

## Acceptance Criteria

* The poll should disappear at 23:59 hours on the target date.
* The real estate of the poll should be reserved on the Home Page.  A message that says "Stay tuned, a new poll is coming soon" should appear if no other poll is active.
* The expiry date should be at least 3 days after the current date.

## Tasks

- [ ] Update the admin module view: the poll design (HTML & CSS) to include date picker.
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon".
- [ ] Create a JavaScript function to validate that the expiry date is after at least 3 days.
- [ ] Create a job to check expired polls everyday at 23:59 hours and hide them.
- [ ] Update the controller function.
- [ ] Update the unit test scripts.
- [ ] Test the functionality.
- [ ] Task 3
