### ISSUE TITLE
USER STORY: Another User Story

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/first-agile-project#8]
In order to **purchase multiple items with one click** as a **customer**, I can **add multiple items to a cart**

## Acceptance Criteria

* Customer can select multiple items and click the 'Add to Cart' button
* Customer can increase the quantity of the items
* Checkout tab lets the user see the items they added, their price and the total price
* Include shipping and offer details

## Tasks

- [ ] Develop a checkbox to each item and an increment and decrement facility
- [ ] Write the functions to perform feature
- [ ] Design the Checkout Page
- [ ] Write the functionality of the Checkout Page
- [ ] Test functionality ...
